### ISSUE TITLE
word_embed.json missing?

### ISSUE THREAD

**Issue by theSage21** [minsangkim142/Fast-Reading-Comprehension#10]
I'm trying to train/demo the code and in both cases, `python config.py --mode train` and `python config.py --mode demo` I end up hitting the same error.

The last few bits of the traceback are:
```
  File "config.py", line 125, in main
    train(config)
  File "/home/arjoonn/Fast-Reading-Comprehension/main.py", line 19, in train
    with open(config.word_emb_file, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'data/word_emb.json'
```

I saw some commented out things in the `download.sh` file, should I be un-commenting those?

**Comment by theSage21** [comment]
I apologize. I'll close this issue once I have reached a laptop and verified that this is indeed what I was doing wrong.

**Comment by theSage21** [comment]
Just saw #11 . If the demo.html is the same as the Rnet I can submit a PR.

**Comment by minsangkim142** [comment]
Could you submit a pr of demo.html? It's identical to rnet's. I'm not with my computer and I won't be for a while but I can approve the pr which fixes the problem from #11. Thanks!

**Comment by minsangkim142** [comment]
Sorry just saw the "ValueError" problem. You should put the "FRC" directory inside "train" directory and keep these lines in config.py.
```
train_dir = "train"
model_name = "FRC"
```

**Comment by theSage21** [comment]
Your closing of the issue made me assume that that was indeed the fix. (y)
