### ISSUE TITLE
OOM error while training

### ISSUE THREAD

**Issue by kamalkraj** [minsangkim142/Fast-Reading-Comprehension#2]
What are  the specification of System you used for training ?

Can you share a pre-trained model weights ?

**Comment by minsangkim142** [comment]
Hi @kamalkraj I uploaded the most recent model pretrained weights (EM/F1 = 70.0/79.4) and you can download it [here](https://drive.google.com/open?id=1gJtcPBNuDr9_2LuP_4x_4VN6_5fQCdfB).

The specification of the system I used is:
CPU: i7-3930K CPU @ 3.20GHz
GPU: GTX1080 (8GB)
RAM: 16GB
Training takes about 5~8 hours depending on your gpu/cpu spec. The model takes about 8 GB gpu memory so if you're using anything bigger than 96 as your hidden unit size then you'll get an OOM error. Or if you are using a preoccupied GPU it will also cause an OOM error.

NOTE: If you are using your desktop GPU, try running it in terminal mode (alt + ctrl + F1) and close all applications that require gpu memory (e.g. Xorg)
`sudo service lightdm stop`
`python config.py --mode train`
after training,
`sudo service lightdm start`
