### ISSUE TITLE
Can it support Chinese?

### ISSUE THREAD

**Issue by jasperzhong** [minsangkim142/Fast-Reading-Comprehension#28]
I just change _nlp = spacy.blank("en")_ to _nlp = spacy.blank("zh")_ 
Is that ok?

**Comment by localminimum** [comment]
Hi, I haven't tried it on Chinese data but I'm assuming a special preprocessing step is required for Chinese characters as they aren't easily separable to characters and words. Also glove word vectors should be changed to Chinese word glove.

**Comment by jasperzhong** [comment]
Yes, spaCy only supports to separate Chinese words. But it does't support other nlp basic functions, such as POS and NER. However, StanfordCoreNLP can do this. 
I wonder whether this model has used other features that needs nlp functions beyond separating words. If so, I suppose I should change StanfordCoreNLP.
And, yes, I used word2vec in Chinese from [here.](https://github.com/Embedding/Chinese-Word-Vectors)

**Comment by maciejbiesek** [comment]
@zhongyuchen Probably it is better to use FastText than w2v :) https://fasttext.cc/docs/en/crawl-vectors.html

**Comment by zhixiaochuan12** [comment]
I wonder if there are any Chinese data sets with same format available for use.
I got the dureader data set from [here](https://github.com/baidu/DuReader), but found the answer is not a span from context.

**Comment by maciejbiesek** [comment]
@yangyuji12 You can try to translate SQuAD paragraphs and questions to Chinese and then find an answer in paragraph (it could be the most difficult part). The authors described this approach in "Data Augmentation by backtranslation" section
