### ISSUE TITLE
How can I do fine tuning using QANet?

### ISSUE THREAD

**Issue by yexing99** [minsangkim142/Fast-Reading-Comprehension#32]
I've trained the QANet model on SQUAD. I wanted to apply this SQUAD trained model to a new dataset using fine tuning. I need to use the weight from this SQUAD trained model as the initialization for the new dataset for training, with a purpose to make the SQUAD model adaptive to the new dataset. 

From the train/FRC folder, I can see there are several checkpoint files. Which checkpoint files should I use for initialization of the new model for the new dataset?

Thanks,

**Comment by localminimum** [comment]
Hi @yexing99 , you can just move the FRC folder into your train folder, and keep these two lines https://github.com/NLPLearn/QANet/blob/8107d223897775d0c3838cb97f93b089908781d4/config.py#L20-L21 and you should be able to train the model from the pretrained weights.

**Comment by localminimum** [comment]
Closing this for now. Feel free to reopen it.
