### ISSUE TITLE
 https://nlp.stanford.edu/data/glove.840B.300d.zip

### ISSUE THREAD

**Issue by zy486at189cn** [minsangkim142/Fast-Reading-Comprehension#39]
First it is a greate job!
The file  https://nlp.stanford.edu/data/glove.840B.300d.zip
could not been download,where can I download it?Thanks!

**Comment by shwetagarg-dev** [comment]
It downloads fine for me.

**Comment by localminimum** [comment]
Hi @zy486at189cn , you can find it [here](https://nlp.stanford.edu/projects/glove/). Put it in your "home/user/datasets/glove", Thanks
