### ISSUE TITLE
AttributeError: 'module' object has no attribute 'blank'

### ISSUE THREAD

**Issue by loveJasmine** [minsangkim142/Fast-Reading-Comprehension#4]
i had done: 
sudo pip install spacy==2.0.9 

mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ python config.py --mode prepro
Traceback (most recent call last):
  File "config.py", line 9, in <module>
    from prepro import prepro
  File "/home/mldl/ub16_prj/Fast-Reading-Comprehension/prepro.py", line 15, in <module>
    nlp = spacy.blank("en")
AttributeError: 'module' object has no attribute 'blank'

**Comment by minsangkim142** [comment]
Have you run `sh download.sh`? Because you also need the english model for spacy to work.
If you've already downloaded the word vectos and squad data then just run
`python3 -m spacy download en`

**Comment by loveJasmine** [comment]
I had "python3 -m spacy download en" done:

but still
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ python config.py --mode prepro
Traceback (most recent call last):
  File "config.py", line 9, in <module>
    from prepro import prepro
  File "/home/mldl/ub16_prj/Fast-Reading-Comprehension/prepro.py", line 15, in <module>
    nlp = spacy.blank("en")
AttributeError: 'module' object has no attribute 'blank'
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ sudo python -m spacy download en
[sudo] password for mldl: 
/usr/bin/python: No module named spacy.__main__; 'spacy' is a package and cannot be directly executed
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$

**Comment by minsangkim142** [comment]
referring to this issue https://github.com/explosion/spaCy/issues/965, maybe try 
`python -m spacy.en.download`?

**Comment by loveJasmine** [comment]
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ sudo python -m spacy.en.download --force
Downloading parsing model
Downloading...
Downloaded 532.28MB 100.00% 3.67MB/s eta 0s              
archive.gz checksum/md5 OK
Model successfully installed to /usr/local/lib/python2.7/dist-packages/spacy/data
Downloading GloVe vectors
Downloading...
Downloaded 708.08MB 100.00% 3.09MB/s eta 0s              
archive.gz checksum/md5 OK
Model successfully installed to /usr/local/lib/python2.7/dist-packages/spacy/data
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$


got the same error yet

what's your scapy version?

**Comment by minsangkim142** [comment]
Try spacy==2.0.9

**Comment by loveJasmine** [comment]
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ sudo pip install spacy==2.0.9
The directory '/home/mldl/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mldl/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting spacy==2.0.9
  Downloading spacy-2.0.9.tar.gz (17.5MB)
    100% |████████████████████████████████| 17.5MB 115kB/s 
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: murmurhash<0.29,>=0.28 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: cymem<1.32,>=1.30 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: thinc<6.11.0,>=6.10.1 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from spacy==2.0.9)
Requirement already satisfied: html5lib==1.0b8 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: pathlib in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: ujson>=1.35 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: dill<0.3,>=0.2 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: regex==2017.4.5 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: ftfy<5.0.0,>=4.4.2 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: msgpack-python==0.5.4 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: msgpack-numpy==0.4.1 in /usr/local/lib/python3.5/dist-packages (from spacy==2.0.9)
Requirement already satisfied: cytoolz<0.9,>=0.8 in /usr/local/lib/python3.5/dist-packages (from thinc<6.11.0,>=6.10.1->spacy==2.0.9)
Requirement already satisfied: wrapt in /usr/local/lib/python3.5/dist-packages (from thinc<6.11.0,>=6.10.1->spacy==2.0.9)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /usr/local/lib/python3.5/dist-packages (from thinc<6.11.0,>=6.10.1->spacy==2.0.9)
Requirement already satisfied: termcolor in /usr/local/lib/python3.5/dist-packages (from thinc<6.11.0,>=6.10.1->spacy==2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests<3.0.0,>=2.13.0->spacy==2.0.9)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests<3.0.0,>=2.13.0->spacy==2.0.9)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests<3.0.0,>=2.13.0->spacy==2.0.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests<3.0.0,>=2.13.0->spacy==2.0.9)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.5/dist-packages (from ftfy<5.0.0,>=4.4.2->spacy==2.0.9)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.5/dist-packages (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy==2.0.9)
Installing collected packages: spacy
  Found existing installation: spacy 2.0.3
    Uninstalling spacy-2.0.3:
      Successfully uninstalled spacy-2.0.3
  Running setup.py install for spacy ... done
Successfully installed spacy-2.0.9
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ python config.py --mode prepro
Traceback (most recent call last):
  File "config.py", line 9, in <module>
    from prepro import prepro
  File "/home/mldl/ub16_prj/Fast-Reading-Comprehension/prepro.py", line 15, in <module>
    nlp = spacy.blank("en")
AttributeError: 'module' object has no attribute 'blank'
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ sudo python -m spacy.en.download 
Downloading parsing model
Model already installed. Please run 'python -m spacy.en.download --force' to reinstall.
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ sudo python -m spacy.en.download --force
Downloading parsing model
Downloading...
Downloaded 532.28MB 100.00% 3.67MB/s eta 0s              
archive.gz checksum/md5 OK
Model successfully installed to /usr/local/lib/python2.7/dist-packages/spacy/data
Downloading GloVe vectors
Downloading...
Downloaded 708.08MB 100.00% 3.66MB/s eta 0s              
archive.gz checksum/md5 OK
Model successfully installed to /usr/local/lib/python2.7/dist-packages/spacy/data
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$ python config.py --mode prepro
Traceback (most recent call last):
  File "config.py", line 9, in <module>
    from prepro import prepro
  File "/home/mldl/ub16_prj/Fast-Reading-Comprehension/prepro.py", line 15, in <module>
    nlp = spacy.blank("en")
AttributeError: 'module' object has no attribute 'blank'
mldl@mldlUB1604:~/ub16_prj/Fast-Reading-Comprehension$

**Comment by minsangkim142** [comment]
It seems that you installed spacy in python3 but downloaded spacy english model in python2. Please use one version or another where you have tensorflow installed.

**Comment by loveJasmine** [comment]
yes,  my 'pip' is for python3, not python2
