### ISSUE TITLE
Train Models With Macs

### ISSUE THREAD

**Issue by ahmedselim2017** [minsangkim142/Fast-Reading-Comprehension#42]
Hi. I have Macbook Air(Mid 2017) and I want to train data. So it haven't a GPU so without GPU how can I train model?

**Comment by leicao-me** [comment]
If you just install tensorflow instead of tensorflow-gpu, you can train with CPU. But it could take you for days.

**Comment by localminimum** [comment]
Hi, if you look at [this issue](https://github.com/NLPLearn/QANet/issues/15), [@ajay-seeram](https://github.com/ajay-sreeram) tried running this experiment in cpu, reported that it took 4 days and a half to train 35k steps.
You can simply install tensorflow in your macbook and follow the steps written in README.md file.

However, **I do not recommend you** training this model in your Mac as it will likely overheat your laptop in no time.
