### ISSUE TITLE
Is this snippet in prepro.py correct

### ISSUE THREAD

**Issue by saxenarohit** [minsangkim142/Fast-Reading-Comprehension#46]
```
 for token in context_tokens:
                    word_counter[token] += len(para["qas"])
                    for char in token:
                        char_counter[char] += len(para["qas"])
```
Should it be +=1?

**Comment by localminimum** [comment]
Hi, thanks for your question! We don't actually use the value of the key in the counters so it's a bit of a redundancy that I should remove. But for consistency it should be +=1 you are correct!
