### ISSUE TITLE
-flags.DEFINE_integer("bucket_range", [40, 401, 40], "the range of bucket")

### ISSUE THREAD

**Issue by loveJasmine** [minsangkim142/Fast-Reading-Comprehension#6]
should be:

-flags.DEFINE_list("bucket_range", [40, 401, 40], "the range of bucket")

**Comment by minsangkim142** [comment]
Fixed. Thanks!

**Comment by wanghm92** [comment]
Does building bucket bring any benefits? like reduction of GPU memory usage? Thanks!
